### ISSUE TITLE
unable to compile master

### ISSUE THREAD

**Issue by bernardpaulus** [kevinherron/pi-server#6]
Dear Kevin,

I also have a Raspberry Pi 3B+ (BCM2835), like in #5 .

According to you advice, I tried to compile from source, but it fails:

```
pi@raspberrypi:~/pi-opcua-server/pi-server $ mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.14.34-v7+", arch: "arm", family: "unix"
pi@raspberrypi:~/pi-opcua-server/pi-server $ mvn clean package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.digitalpetri.piserver:pi-server:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 123, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 168, column 21
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:buildnumber-maven-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 139, column 21
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.digitalpetri.piserver:pi-server-jsw:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 123, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 168, column 21
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:buildnumber-maven-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 139, column 21
[WARNING] The expression ${pom.version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.digitalpetri.piserver:sensor-plugin:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 123, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 168, column 21
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:buildnumber-maven-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 139, column 21
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.digitalpetri.piserver:sensor-plugin-grovepi:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.digitalpetri.piserver:sensor-plugin-grovepi:[unknown-version], /home/pi/pi-opcua-server/pi-server/sensor-plugin-grovepi/pom.xml, line 36, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 168, column 21
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:buildnumber-maven-plugin is missing. @ com.digitalpetri.piserver:pi-server-parent:2.0.0-SNAPSHOT, /home/pi/pi-opcua-server/pi-server/pom.xml, line 139, column 21
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.digitalpetri.piserver:pi-server-parent:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 123, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 168, column 21
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:buildnumber-maven-plugin is missing. @ line 139, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] PiServer
[INFO] pi-server
[INFO] pi-server-jsw
[INFO] sensor-plugin
[INFO] sensor-plugin-grovepi
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building PiServer 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pi-server-parent ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ pi-server-parent ---
[INFO] ShortRevision tag detected. The value is '10'.
[INFO] Executing: /bin/sh -c cd '/home/pi/pi-opcua-server/pi-server' && 'git' 'rev-parse' '--verify' '--short=10' 'HEAD'
[INFO] Working directory: /home/pi/pi-opcua-server/pi-server
[INFO] Storing buildNumber: 6d120a0a97 at timestamp: 1530187274569
[WARNING] Cannot get the branch information from the git repository:
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] ShortRevision tag detected. The value is '10'.
[INFO] Executing: /bin/sh -c cd '/home/pi/pi-opcua-server/pi-server' && 'git' 'rev-parse' '--verify' '--short=10' 'HEAD'
[INFO] Working directory: /home/pi/pi-opcua-server/pi-server
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default) @ pi-server-parent ---
[INFO] No sources to compile
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building pi-server 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.eclipse.milo:sdk-server:jar:0.1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] PiServer ........................................... SUCCESS [  3.524 s]
[INFO] pi-server .......................................... FAILURE [  0.262 s]
[INFO] pi-server-jsw ...................................... SKIPPED
[INFO] sensor-plugin ...................................... SKIPPED
[INFO] sensor-plugin-grovepi .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.402 s
[INFO] Finished at: 2018-06-28T12:01:16+00:00
[INFO] Final Memory: 9M/21M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pi-server: Could not resolve dependencies for project com.digitalpetri.piserver:pi-server:jar:2.0.0-SNAPSHOT: Could not find artifact org.eclipse.milo:sdk-server:jar:0.1.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pi-server
```
 I'll fork, and notify you if I have a fix :)

Kind regards,

Bernard

**Comment by kevinherron** [comment]
It looks like the dependencies on Milo are pointing at SNAPSHOT artifacts that no longer exist...

I think I've started "rescuing" this project locally, and have it compiling, but not it's functional again...

**Comment by kevinherron** [comment]
I just pushed changes to master that enable it to compile against the latest Milo 0.3.0-SNAPSHOT. 

You'll probably have to check out the `dev/0.3` branch of [Milo](https://github.com/eclipse/milo) and `mvn install` it so the SNAPSHOT artifacts don't keep disappearing on you.

**Comment by bernardpaulus** [comment]
My repo compiles as of https://github.com/bernardpaulus/pi-server/commit/b63a44fdfd629f331e6920dcc3c525688de3f13d

Personally I preferred to comment out the oss.sonatype repo and base myself on what was available on maven-central because I love reproducible builds ( therefore, no snapshot articfacts outside the project )

I had to scratch out the dependency on `com.digitalpetri.piserver:sensor-grovepi` from `pi-server-jsw`.

Do you know where I can find it?

I have the problem in #5 ... gonna focus on that

**Comment by kevinherron** [comment]
The GrovePi4J library this needs is [here](https://github.com/kevinherron/GrovePi4J).

The latest version of pi-server (current master) doesn't have that exact dependency you mention.

**Comment by bernardpaulus** [comment]
Ok, I had a problem with my touchpad which probably made me accidentally delete a part of the dependency name. I [reverted that](https://github.com/kevinherron/pi-server/commit/3533d3860839242b85f6dd7652aaa006781cfd6b)

**Comment by bernardpaulus** [comment]
My version compiles. I still have the following problem with yours:

```
[ERROR] Failed to execute goal on project pi-server: Could not resolve dependencies for project com.digitalpetri.piserver:pi-server:jar:2.0.0-SNAPSHOT: Could not find artifact org.eclipse.milo:sdk-server:jar:0.3.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pi-server
```

Why do you insist on using Milo 0.3.0-SNAPSHOT ?

**Comment by kevinherron** [comment]
`0.3.0-SNAPSHOT` is the current development version and has functionality I want and API changes. There is no release yet. `pi-server` is also in a development state right now, so there's no harm. I don't typically include SNAPSHOT artifacts in a "releasable" project.

**Comment by bernardpaulus** [comment]
ok :)

So you need to compile https://github.com/eclipse/milo/tree/dev/0.3 locally to make it work

I'm taking another direction for now, so I won't look into it for now, but thank you for all the replies!

**Comment by kevinherron** [comment]
Sure, no problems.

This project was something I threw together very quickly for a tradeshow a few years ago. It's not very useful for anything, but people keep finding it and trying to use it!

I've been considering building a more generic IoT Sensor OPC UA server on top of Intel's [upm](https://github.com/intel-iot-devkit/upm) library, which would mean support for more boards and many many more sensors than just the handful of GrovePi's I had on hand when I built it.
